# Generated by Django 5.2.5 on 2025-08-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('victim', 'Victim'), ('volunteer', 'Volunteer'), ('authority', 'Authority')], default='victim', max_length=20),
        ),
    ]
