# Generated by Django 5.2.5 on 2025-08-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencies', '0002_donation_sosalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='sosalert',
            name='type',
            field=models.CharField(choices=[('fire', 'Fire'), ('medical', 'Medical'), ('other', 'Other')], default='medical', max_length=50),
        ),
    ]
