# Generated by Django 5.2.5 on 2025-08-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencies', '0003_sosalert_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='quantity',
            field=models.CharField(max_length=255),
        ),
    ]
