# Generated by Django 5.2.5 on 2025-08-18 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencies', '0004_alter_donation_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sosalert',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_sos_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sosalert',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sosalert',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='sosalert',
            name='volunteers',
            field=models.ManyToManyField(blank=True, related_name='sos_volunteerings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sosalert',
            name='volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_sos_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
